fix(2151): helm-release-v12.1.0 (#186)
- Fix for error: uncaughtException: Cannot find module 'ajv'
- Bump to patch version

Co-authored-by: Sam <10507686+elnyry-sam-k@users.noreply.github.com>